charbucket/charapp/urls.py
from django.urls import path
from . import views

app_name = 'charapp'
urlpatterns = [
    path('', views.userhome, name='userhome'),
    path('nu_post/', views.nu_post, name='nu_post'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('comment/<int:post_id>/', views.comment, name='comment'),
    path('table/<int:post_id>/', views.post_table, name='post_table'),
    path('quickroom/<str:room_key>/', views.quickstart, name='quickstart'),
]

charbucket/charbucket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('charapp/', include('charapp.urls')),
    path('trix/', include('trix.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

charbucket/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.login_register, name='login_register'),
    path('register_user/', views.register_user, name='register_user'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
]

charbucket/charapp/models.py
from django.db import models
from django.contrib.auth.models import User
from trix.fields import TrixField

class Post(models.Model):
    user = models.ForeignKey(User, related_name = 'posts', on_delete = models.CASCADE)
    text = models.TextField()
    title = models.CharField(max_length = 50, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add = True)    

    def __str__(self):
        return f'{self.user.username} - {self.title}'

class Comment(models.Model):
    user = models.ForeignKey(User, related_name = 'comments', on_delete = models.CASCADE)
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey(Post, related_name = 'comments', on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.text}'

charbucket/charapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.safestring import mark_safe
from .models import Post, User, Comment
import json
import string
import random

def userhome(request):
    posts = request.user.posts.all()
    userlist = User.objects.all()
    context = {
        'posts':posts,
        'userlist':userlist,
    }
    return render(request, 'charapp/userhome.html', context)

def nu_post(request):
    user = request.user
    text = request.POST['nu_post_text']
    if text: 
        print(text)
    else: print('broke')
    title = request.POST['nu_post_title']

    post = Post.objects.create(user=user, text=text, title=title)
    post.save()

    return HttpResponseRedirect(reverse('charapp:userhome'))

def profile(request, username):
    context = {
        'profile': User.objects.get(username = username),
        'userlist': User.objects.all(),
    }
    return render(request, 'charapp/profile.html', context)

def comment(request, post_id):
    commenter = request.user
    post = Post.objects.get(id = post_id)
    text = request.POST['comment_text']
    author_name = request.POST['profile']

    comment = Comment.objects.create(user = commenter, post = post, text = text)
    comment.save()

    return HttpResponseRedirect(reverse('charapp:profile', args = [author_name]))

def post_table(request, post_id):
    post = Post.objects.get(id = post_id)
    user = request.user
    return render(request, 'charapp/post_table.html', {
        'user': user,
        'post': post,
    })

def quickstart(request, room_key):
    user = ''.join([random.choice(string.ascii_letters) for i in range(8)])
    context = {
        'user': user,
        'roomkey': room_key, 
    }
    return render(request, 'charapp/quickroom.html', context)
    
    

charbucket/users/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def login_register(request):
    return render(request, 'users/login_register.html')


def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    login(request, user)

    return HttpResponseRedirect(reverse('charapp:userhome'))

def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None: # username and password matched a user
        login(request, user)
        return HttpResponseRedirect(reverse('charapp:userhome'))
    else:
        return HttpResponseRedirect(reverse('users:login_register'))



def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login_register'))

charbucket/charapp/templates/charapp/post_table.html
{% extends 'charbucket/base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <p>logged in as {{user.username}}</p>
            <p>{{post.title}} - {{post.user}}</p>
        </div>
        <div class="card-body d-flex">
            <div class="col">
                <input id="whiteboardInput" type="hidden" value="{{post.text|safe}}">
                <trix-toolbar id="wbtools">
                    {% if post.user == user %}
                    <button id="wbtools-save" class="btn btn-secondary">save</button>
                    <button id="wbtools-set" class="btn btn-secondary">set</button>
                    <button id="wbtools-restore" class="btn btn-secondary">restore</button>
                    {% endif %}
                    <div class="spinner-grow text-primary" id="wbtools-indicator" style="display:none" role="alert"></div>
                    <p class="wbtools-indicator-el" id="wbtools-indicator-label" style="display:none"></p>
                </trix-toolbar>
                <trix-editor class="trixcon" input="whiteboardInput" toolbar="wbtools" id="whiteboard" contenteditable="true"></trix-editor>
            </div>

            <div class="col comment_box">
                <ul id="comment_block" class="list-group list-group-flush">
                    {% for comment in post.comments.all %}
                    <li class="list-group-item">{{comment}}</li>
                    {% endfor %}
                </ul>
                <input id = "comment_input" type = "text"/>
                <br>
                <!-- <input id = "comment_submit" type="button" value="Send"/> -->
                <button id="comment_submit" type="button" class="btn btn-secondary">Send</button>
            </div>
        </div>
        </div>
    </div>

<script type="text/javascript">

    let commSocket = new WebSocket(
        'ws://' + window.location.host + 
        '/ws/charapp/table/{{post.id}}/'
    );

    commSocket.onmessage = function(e) {
        console.log('message received by client');
        let data = JSON.parse(e.data);
        // console.log(data);
        // console.log(JSON.parse(data.text))
        // console.log(data.text)
        // console.log(JSON.parse(JSON.parse(data.text)))
        // data = JSON.parse(data.text)
        data = JSON.parse(data.text)
        console.log(data)

        if (data['llama'] == 'comment') {
            let message = data['message'];
            let li = document.createElement('li');
            li.innerHTML = data['user'] + ': ' + data['comment']
            li.classList.add('list-group-item')
            let comBlock = document.querySelector('#comment_block')
            comBlock.appendChild(li)
        }
        
        if (data['llama'] == 'alteration') {
            
            if (data['userID'] != {{user.id}}) {
                console.log('setting editor')
                denyInput(data['user'])
                let range = whiteboard.editor.getSelectedRange();
                let userID = data['userID'];
                document.querySelector('#whiteboard').editor.loadJSON(data['message']);
                whiteboard.editor.setSelectedRange(range);
            } else {console.log('same origin')};
            // indicator.style.display = 'none'
        };


    };

    commSocket.onclose = function(e) {
        console.error('Websocket closed unexpectedly');
    };

    let inputFlag = false;
    let timer = 0
    let setTimer

    function denyInput(user) {
        console.log(inputFlag)
        if (inputFlag === false) {
        document.querySelector('#wbtools-indicator').style.display = 'inline-block';
        if (document.querySelector('#wbtools-indicator-label').style.display = 'inline-block') {console.log('i dont know why this works but ok')}
        document.querySelector('#wbtools-indicator-label').innerText = user + ' is typing'        
        whiteboard.contenteditable = 'false';
        inputFlag = true
        if (timer < 3) {timer += 1}
        console.log('disabling input')
        setTimer = setInterval(reverseDeny, 1000)
        } else {
            if (timer < 3) {timer += 1}
        }
    }


    function reverseDeny() {
        console.log('interval...', timer)
        if (timer === 0) {
        console.log('zero caught')
        document.querySelector('#wbtools-indicator').style.display = 'none';
        document.querySelector('#wbtools-indicator-label').style.display = 'none';
        whiteboard.contenteditable = 'true';
        inputFlag = false
        console.log('enabling input')
        clearTimer()
        } else {
            timer -= 1
        }
    }
    
    function clearTimer() {
        console.log('clearing interval');
        clearInterval(setTimer);
    }

    comment_submit.onclick = function(e) {
        let post = {{post.id}};
        let user = {{user.id}};
        let commTextInput = document.querySelector('#comment_input');
        let commText = commTextInput.value;
        commSocket.send(JSON.stringify({
            'llama': 'comment',
            'commText': commText,
            'userID': user,
            'postID': post,
        }));
        commTextInput.value = '';
    };

    whiteboard.addEventListener('trix-change', _.debounce(function(e) {
        if (inputFlag) {
            console.log('listener disabled');
            return;
        }
        console.log('sending')
        let userID = {{user.id}};
        let user = '{{user.username}}';
        let whiteboardData = whiteboard.editor;
        commSocket.send(JSON.stringify({
            'llama': 'alteration',
            'userID': userID,
            'user': user,
            'whiteboard': whiteboardData,
        }));
        // let whiteboard = document.querySelector('#whiteboard').editor;
        // let userID = {{user.id}};
        // commSocket.send(JSON.stringify({
        //     'type': 'alteration',
        //     'userID': userID,
        //     'whiteboard': whiteboard,
        // }));
    }, 300));
    
    // whiteboard.ontrixchange = sendAlter();

    // let restorePoint = null
    // window.onload = function() {
    //     whiteboard.editor.loadJSON(JSON.parse('{{post.text|safe}}'))
    //     restorePoint = JSON.stringify(whiteboard.editor);
    // }
    
    let restorePoint = null

    window.onload = function() {
        restorePoint = JSON.stringify(whiteboard.editor)
        console.log(restorePoint)
    }

    if (document.querySelector('#wbtools-save') !== null) {
        document.querySelector('#wbtools-save').addEventListener('click', function() {
            let whiteboardData = whiteboardInput.value;
            restorePoint = JSON.stringify(whiteboard.editor);
            console.log(restorePoint)
            commSocket.send(JSON.stringify({
                'llama': 'saveAlter',
                'postID': {{post.id}},
                'whiteboard': whiteboardData,
            }))
        });
    }
    if (document.querySelector('#wbtools-set') !== null) {
        document.querySelector('#wbtools-set').addEventListener('click', function() {
            console.log('heard set')
            restorePoint = JSON.stringify(whiteboard.editor);
        });
    }

    if (document.querySelector('#wbtools-restore') !== null) {
        document.querySelector('#wbtools-restore').addEventListener('click', function() {
            console.log('heard restore')
            whiteboard.editor.loadJSON(JSON.parse(restorePoint))
        });
    }

</script>
{% endblock%}

charbucket/charapp/templates/charapp/profile.html
{% extends 'charbucket/base.html' %}
{% block content %}

    <div class="container">
        <h3>{{profile.username}} profile</h3>
        {% for post in profile.posts.all %}
        <div class="card m-3">
                <div class="card-header">
                    {{post.title}}
                </div>
                <div class="card-body d-flex">
                    <div class="card-text col-sm trixprev">
                        {{post.text|safe}}
                    </div>
                    {% if post.upload %}
                    <iframe class="col-sm" src="{{post.upload.url}}" frameborder="0" allowfullscreen="True" seamless="True"></iframe>
                    {% endif %}
                    <div class="comment_box comment-prev">
                    <ul class="list-group list-group-flush">
                        {% for comment in post.comments.all %}
                        <li class="list-group-item">{{comment}}</li>
                        {% endfor %}
                    </ul>
                    </div>
                </div>
                <div class="card-footer">
                    <a type="button" class="btn btn-secondary" href="{% url 'charapp:post_table' post.id %}">View</a>
                </div>
                <script>

                </script>
            </div>
        {% endfor %}
    </div>
    <div class="container">
        <h3>user directory</h3>
        {% for user in userlist %}
        <a href="{% url 'charapp:profile' user.username %}">{{user}}</a> <br>
        {% endfor %}
    </div>
{% endblock %}

charbucket/charapp/templates/charapp/quickroom.html
{% extends 'charbucket/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="card w-100">
            <div class="card-header">
                <p>room key = {{roomkey}}</p>
                <p>userID = {{user}}</p>
            </div>
            <div class="card-body d-flex">
                <div class="col">
                    <input id="whiteboardInput" type="hidden" value="{{post.text|safe}}">
                    <trix-toolbar id="wbtools">
                        <button id="wbtools-set" class="btn btn-secondary">set</button>
                        <button id="wbtools-restore" class="btn btn-secondary">restore</button>
                        <div class="spinner-grow text-primary wbtools-indicator-el" id="wbtools-indicator" style="display:none" role="alert"></div>
                        <p class="wbtools-indicator-el" id="wbtools-indicator-label" style="display:none"></p>
                    </trix-toolbar>
                    <trix-editor class="trixcon" input="whiteboardInput" toolbar="wbtools" id="whiteboard" contenteditable="true"></trix-editor>
                </div>
    
                <div class="col comment_box">
                    <ul id="comment_block" class="list-group list-group-flush"></ul>
                    <input id = "comment_input" type = "text"/>
                    <br>
                    <button id="comment_submit" type="button" class="btn btn-secondary">Send</button>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    let commSocket = new WebSocket(
        'ws://' + window.location.host + 
        '/ws/charapp/quickroom/{{roomkey}}/'
    );

    let wbtIndicator = document.querySelector('#wbtools-indicator')
    let wbtLabel = document.querySelector('#wbtools-indicator-label')
    let wbtSet = document.querySelector('#wbtools-set')
    let wbtRestore = document.querySelector('#wbtools-restore')
    let whiteboard = document.querySelector('#whiteboard')
    let comBlock = document.querySelector('#comment_block')
    let comInput = document.querySelector('#comment_input')

    commSocket.onmessage = function(e) {
        console.log('message received by client');
        let data = JSON.parse(e.data);
        data = JSON.parse(data.text)
        console.log(data)

        if (data['llama'] == 'qComment') {
            console.log(data['user'])
            let message = data['message'];
            let li = document.createElement('li');
            li.innerHTML = data['userID'] + ': ' + data['comment']
            li.classList.add('list-group-item')
            comBlock.appendChild(li)
        }
        
        if (data['llama'] == 'qAlteration') {
            
            if (data['userID'] != '{{user}}') {
                console.log('setting editor')
                denyInput(data['userID'])
                let range = whiteboard.editor.getSelectedRange();
                let userID = data['userID'];
                whiteboard.editor.loadJSON(data['message']);
                whiteboard.editor.setSelectedRange(range);
            } else {console.log('same origin')};
        };


    };

    commSocket.onclose = function(e) {
        console.error('Websocket closed unexpectedly');
    };

    let inputFlag = false;
    let timer = 0
    let setTimer

    function denyInput(user) {
        console.log(inputFlag)
        if (inputFlag === false) {
        wbtIndicator.style.display = 'inline-block';
        wbtLabel.style.display = 'inline-block';
        wbtLabel.innerText = user + ' is typing'
        whiteboard.contenteditable = 'false';
        inputFlag = true
        if (timer < 3) {timer += 1}
        console.log('disabling input')
        setTimer = setInterval(reverseDeny, 1000)
        } else {
            if (timer < 3) {timer += 1}
        }
    }


    function reverseDeny() {
        console.log('interval...', timer)
        if (timer === 0) {
        console.log('zero caught')
        wbtIndicator.style.display = 'none';
        wbtLabel.style.display = 'none';
        whiteboard.contenteditable = 'true';
        inputFlag = false
        console.log('enabling input')
        clearTimer()
        } else {
            timer -= 1
        }
    }
    
    function clearTimer() {
        console.log('clearing interval');
        clearInterval(setTimer);
    }

    comment_submit.onclick = function(e) {
        let user = '{{user}}';
        let commTextInput = document.querySelector('#comment_input');
        let commText = comInput.value;
        commSocket.send(JSON.stringify({
            'llama': 'qComment',
            'commText': commText,
            'userID': user,
        }));
        commTextInput.value = '';
    };

    whiteboard.addEventListener('trix-change', _.debounce(function(e) {
        if (inputFlag) {
            console.log('listener disabled');
            return;
        }
        console.log('sending')
        let userID = '{{user}}';
        let whiteboardData = whiteboard.editor;
        commSocket.send(JSON.stringify({
            'llama': 'qAlteration',
            'userID': userID,
            'whiteboard': whiteboardData,
        }));
    }, 300));
    
    let restorePoint = null

    window.onload = function() {
        restorePoint = JSON.stringify(whiteboard.editor)
        console.log(restorePoint)
    }

    wbtSet.addEventListener('click', function() {
        console.log('heard set')
        restorePoint = JSON.stringify(whiteboard.editor);
    });

    wbtRestore.addEventListener('click', function() {
        console.log('heard restore')
        whiteboard.editor.loadJSON(JSON.parse(restorePoint))
    });

</script>
{% endblock%}

charbucket/charapp/templates/charapp/userhome.html
{% extends 'charbucket/base.html' %}
{% block content%}
<script>
</script>
    <div class="container">
        <button class="btn btn-primary" data-toggle="collapse" data-target="#nu_post_form">New Post</button>
        <div class="collapse" id="nu_post_form">
            <form action="{% url 'charapp:nu_post' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <input type="text" name="nu_post_title" placeholder="title"/>
            <input type="hidden" id="nu_post_text" name="nu_post_text">
            <trix-toolbar id="nptools"></trix-toolbar>
            <trix-editor input="nu_post_text" toolbar="nptools"></trix-editor>
            <button class="btn btn-primary" type="submit">submit</button>
            </form>
        </div>
        
    </div>
    <div class="container">
        <h3>user directory</h3>
        {% for user in userlist %}
        <a href="{% url 'charapp:profile' user.username %}">{{user}}</a> <br>
        {% endfor %}
    </div> 
    <div class="container">
        <h3>Posts</h3>
        {% for post in posts %}
        <div class="card">
            <div class="card-header">
                {{post.title}}
                <a type="button" class="btn btn-primary" href="{% url 'charapp:post_table' post.id %}">View Post</a>
            </div>
            <div class="card-body d-flex">
                <div class="card-text col-sm trixprev">
                    {{post.text|safe}}
                </div>
                {% if post.upload %}
                <iframe class="col-sm" src="{{post.upload.url}}" frameborder="0" allowfullscreen="True" seamless="True"></iframe>
                {% endif %}
                <div class="comment-prev">
                <ul class="list-group list-group-flush">
                    {% for comment in post.comments.all %}
                    <li class="list-group-item">{{comment}}</li>
                    {% endfor %}
                </ul>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}

charbucket/templates/charbucket/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
    <link href="{% static 'trix/trix.css' %}" rel="stylesheet">
    <script src="{% static 'trix/trix.js' %}"></script>
    <title></title>
    <style>
    .trixcon {
      overflow-y: auto !important;
      max-height: 30em !important;
      max-width: inherit !important;
    }
    .comment_box {
      max-height: 30em !important;
      max-width: inherit !important;
      overflow-y: auto;
    }
    .trixprev {
      overflow-y: auto !important;
      max-height:15em !important;
      max-width: inherit !important;
    }
    .comment-prev {
      max-height: 15em !important;
      max-width: inherit !important;
      overflow-y: auto;
    }
    .theme-material {
      background-color: #e8eff1;
      color: #1a1a1c;
    }
    .header-material {
      background-color: #43b0f1;
      color: #1a1a1c;
    }
    .theme-nightmode {
      background-color: #1a1a1c;
      color: #e8eff1;
    }
    .header-nightmode {
      background-color: #0c0c0d;
      color: #e8eff1;
    }
    .theme-lemmonchiffon {
      background-color: lemonchiffon;
      color: #2a0412;
    }
    .theme-lemmonchiffon > * {
      background-color: lemonchiffon;
      color: #2a0412;
    }
    .header-lemmonchiffon {
      background-color: #daf7a6;
      color: #2626f2;
    }
    </style>
  </head>
  <body id="bodyTag" class="theme-material">
    <header id="headerTag" class="container header-material">
      <div class="row justify-content-between align-items-center">
        <div class="col-4">
            <h2>cuttingrooms</h2>
            <p>a virtual writerspace</p>
        </div>
        <div class="col-4">
            <a type="button" class="btn btn-secondary" href="{% url 'charapp:userhome' %}">home</a>
        </div>
      </div>
      <!-- <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
            choose theme
          </button>
        <div class="dropdown-menu" id="modeselect">
          <div class="dropdown-item" name="material" id="material-select">material</div>
          <div class="dropdown-item" name="nightmode" id="nightmode-select">nightmode</div>
          <div class="dropdown-item" name="lemonchiffon" id="lemonchiffon-select">lemmonchiffon</div>
        </div>
      </div> -->
    </header>
    {% block content %}
    {% endblock %}
    <!-- <script>
      let bodyTag = document.querySelector('#bodyTag')
      let modeselect = document.querySelector('.dropdown-item')
      let headerTag = document.querySelector('#headerTag')
      modeselect.addEventListener('click', modeSwap(modeselect.value))
      function modeSwap(val) {
        if (val == 'material') {
          bodyTag.className = ''
          bodyTag.classList.add('theme-material')
          headerTag.className = ''
          headerTag.classList.add('header-material') 
        } else if (val == 'nightmode') {
          bodyTag.className = ''
          bodyTag.classList.add('theme-nightmode')
          headerTag.className = ''
          headerTag.classList.add('header-nightmode')
        } else if (val == 'lemmonchiffon') {
          bodyTag.className = ''
          bodyTag.classList.add('theme-lemmonchiffon')
          headerTag.className = ''
          headerTag.classList.add('header-lemmonchiffon')
        } else {
          console.log(val)
        }
        
      } -->
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

charbucket/users/templates/users/login_register.html
{% extends 'charbucket/base.html' %}
{% block content %}
<div class="container card min-vh-100 d-flex flex-col justify-content-center">

  <div class="row justify-content-center">
    <h3>Quickstart</h3>
  </div>
  <div class="row justify-content-center pb-5">
    <input type="text" name="quick-key-input" id="quick-key-input" placeholder="type or paste room key: press enter">
    <button class="btn btn-secondary" id="enter-new-room">new room</button>
  </div>
  <div class="row justify-content-center">
    <h3>Login</h3>
  </div>
  <div class="row justify-content-center pb-5">
    <form action="{% url 'users:login_user' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="username" required/>
      <input type="password" name="password" placeholder="password" required/>
      <button type="submit" class="btn btn-secondary">Login</button>
    </form>
  </div>
  <div class="row justify-content-center">
  <h3>Register</h3>
  </div>
  <div class="row justify-content-center pb-5">
    <form action="{% url 'users:register_user'  %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="username" required/>
      <input type="email" name="email" placeholder="email" required/>
      <input type="password" name="password" placeholder="password" required/>
      <button type="submit" class="btn btn-secondary">Register</button>
    </form>
  </div>

<!-- style="display:flex;flex-direction:column;justify-content:center" -->
</div>
<script type="text/javascript">

document.querySelector('#quick-key-input').addEventListener('keydown', function(e) {
  let key = document.querySelector('#quick-key-input').value
  if (e.keyCode == 13) {
    window.location.pathname = 'charapp/quickroom/' + key +'/'
    }
  }
);


document.querySelector('#enter-new-room').addEventListener('click', function() {
  newKey = [];
  for (i = 0; i<10; i++) {newKey.push(_.random(10))};
  newKey = newKey.join('');
  newKey
  window.location.pathname = 'charapp/quickroom/' + newKey + '/';
});

</script>
{% endblock %}